import telebot
import os
from dotenv import load_dotenv
from prediction_module import isReviewReal,text_process


load_dotenv(dotenv_path=os.path.join(os.getcwd(),'.env'))
token = os.getenv("BOT_TOKEN")
bot = telebot.TeleBot(token)

#Function that handles the response to the start command
@bot.message_handler(commands=["start"])
def start(message):
    bot.reply_to(message, "Hi! Welcome to FakeReviewDetector, send me a review to check it")

#Function that handles the response to the help command
@bot.message_handler(commands=["help"])
def help(message):
    bot.reply_to(message,"With this bot, you can check whether a review is true or fake (generated by bots). Just send a review in the form of a message and you’re done!")

#Function that handles the response to the quit command
@bot.message_handler(commands=["quit"])
def quit(message):
    bot.reply_to(message, "Bye! Thanks for using FakeReviewDetector")
    bot.stop_polling()

#Function that handles the review sent in the form of a message
@bot.message_handler()
def message(message):
    recensione = message.text
    prediction = isReviewReal(recensione)
    if prediction == True:
        bot.reply_to(message,"The review you submitted is true and was therefore written by a human")
    else:
        bot.reply_to(message,"You submitted a bot-written review, which means that it is not authentic")

#Start listening to incoming messages from users
bot.polling()